########################################################################
# Description:
# Project Tools configuration
########################################################################

[tool.isort]
profile = "black"